---
engines:
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      global-require:
         enabled: false
      handle-callback-err:
         enabled: false
      Similar code:
         enabled: false
      no-process-exit:
         enabled: false
      exclude_fingerprints:
         - 9801ff54e320c64e928f3a1c20dbf247
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- test/
