branches:
   only:
      - master
language: node_js
node_js:
   - "5.7.0"
install:
   - npm install coveralls
   - npm install codeclimate-test-reporter
   - npm install -g gulp
   - npm install
script:
   - gulp ci
   - coveralls
after_success:
   - codeclimate-test-reporter < coverage/lcov.info
   - codacy-covarage < coverage/lcov.info
