branches:
   only:
      - master
language: node_js
node_js:
   - "5.7.0"
before_install:
   - pip install --user :codecov
install:
   - npm install -g gulp
   - npm install
script:
   - gulp ci
after_success:
   - codecov
