branches:
   only:
      - master
language: node_js
os:
   - linux
   - osx
node_js:
   - "5.7.0"
install:
   - npm install coveralls
   - npm install codeclimate-test-reporter
   - npm install -g gulp
   - npm install
cache:
   directories:
      - node_modules
script:
   - gulp ci
after_success:
   - ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info 
   - ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < coverage/lcov.info
   - ./node_modules/codacy-coverage/bin/codacy-coverage.js < coverage/lcov.info
